name: Deploy Python App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Verify Repository Checkout
      run: |
        echo "Checking repository contents..."
        ls -la
        echo "Current branch: $(git rev-parse --abbrev-ref HEAD)"
        echo "Last commit: $(git log -1 --oneline)"

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_SSH_KEY }}
        script: |
          # Debugging: Verify that the directory exists and list contents
          echo "Checking directory ~/python-deploy on EC2"
          ls -la ~/python-deploy

          # Pull the latest code from GitHub repository
          echo "Pulling latest changes from GitHub"
          cd ~/python-deploy || (git clone https://github.com/tarunsadhukhan/python-deploy.git ~/python-deploy && cd ~/python-deploy)
          git pull origin main || git fetch --all && git reset --hard origin/main
          
          # Debugging: Check the contents of the directory after pulling changes
          echo "Contents of ~/python-deploy after pulling changes:"
          ls -la ~/python-deploy

          # Build the Docker image
          echo "Building Docker image"
          docker build -t python-deploy . || (echo "Docker build failed" && exit 1)
          
          # Debugging: Verify Docker image build and running containers
          echo "Listing Docker images:"
          docker images
          
          # Stop and remove the old container, then run the new one
          echo "Stopping and removing old container if exists"
          docker stop python-deploy || true
          docker rm python-deploy || true
          
          echo "Starting new container"
          docker run -d -p 5004:5004 --name python-deploy python-deploy
          
          # Debugging: Verify running Docker containers
          echo "Listing running Docker containers:"
          docker ps
