name: Build and Deploy to Amazon ECR

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up AWS CLI and Podman
      - name: Set up AWS CLI and Podman
        run: |
          sudo apt update
          sudo apt install -y awscli podman

      # Step 3: Log in to Amazon ECR
      - name: Log in to Amazon ECR
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | podman login --username AWS --password-stdin ${{ secrets.AWS_ECR_URL }}

      # Step 4: Build Docker Image using Podman
      - name: Build Docker Image using Podman
        run: |
          podman build -t ${{ secrets.AWS_ECR_URL }}/python-deploy:latest .

      # Step 5: Push Docker Image to Amazon ECR
      - name: Push Docker Image to Amazon ECR
        run: |
          podman push ${{ secrets.AWS_ECR_URL }}/python-deploy:latest

      # Step 6: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_USER@$EC2_HOST <<EOF
            # Ensure Docker is installed
            if ! command -v podman &> /dev/null; then
              sudo apt update
              sudo apt install -y podman
            fi
            
            # Pull the latest image from ECR
            podman pull ${{ secrets.AWS_ECR_URL }}/pyhon-deploy:latest
            
            # Stop and remove any existing container
            podman stop python-app || true
            podman rm python-app || true
            
            # Run the container with the pulled image
            podman run -d --name python-deploy -p 80:5005 ${{ secrets.AWS_ECR_URL }}/python-deploy:latest
          EOF
