name: Build and Deploy to AWS EC2

on:
  push:
    branches:
      - main  # Runs on every push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python-deploy:latest .

      # Step 4: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/python-deploy:latest

      # Step 5: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_USER@$EC2_HOST <<EOF
            # Install Docker if not installed
            if ! command -v docker &> /dev/null
            then
                sudo apt update
                sudo apt install -y docker.io
                sudo systemctl start docker
                sudo systemctl enable docker
                sudo usermod -aG docker \$USER
            fi

            # Stop and remove old container if exists
            docker stop python-app || true
            docker rm python-app || true

            # Pull and run the new container
            docker pull ${{ secrets.DOCKER_USERNAME }}/python-deploy:latest
            docker run -d --name python-app -p 80:5000 ${{ secrets.DOCKER_USERNAME }}/python-deploy:latest
          EOF
