name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust if needed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to AWS ECR
      - name: Log in to AWS ECR
        run: |
          aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 776929205174.dkr.ecr.eu-north-1.amazonaws.com

      # Step 3: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t 776929205174.dkr.ecr.eu-north-1.amazonaws.com/python-deploy:latest .
          docker push 776929205174.dkr.ecr.eu-north-1.amazonaws.com/python-deploy:latest

      # Step 4: Deploy on AWS EC2
      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ubuntu
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_USER@$EC2_HOST <<EOF
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt update
              sudo apt install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
              sudo usermod -aG docker ubuntu
            fi
            
            # Log in to AWS ECR on EC2
            aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 776929205174.dkr.ecr.eu-north-1.amazonaws.com
            
            # Pull the latest image and run it
            docker pull 776929205174.dkr.ecr.eu-north-1.amazonaws.com/python-deploy:latest
            docker stop python-app || true
            docker rm python-app || true
            docker run -d --name python-app -p 80:5004 776929205174.dkr.ecr.eu-north-1.amazonaws.com/python-deploy:latest
          EOF
