name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main  # Adjust this to match your branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Registry
      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t tarunksadhukhan/python_deploy:latest .

      # Step 4: Push Docker Image to Registry
      - name: Push Docker Image
        run: |
          docker push tarunksadhukhan/python-deploy:latest

      # Step 5: Deploy to AWS EC2
      - name: Deploy to AWS EC2
        env:
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private-key.pem
          chmod 600 private-key.pem
          ssh -o StrictHostKeyChecking=no -i private-key.pem $EC2_USER@$EC2_HOST <<EOF
            docker pull tarunksadhukhan/python_deploy:latest
            docker stop python-app || true
            docker rm python-app || true
            docker run -d --name python-app -p 5005:5004 tarunksadhukhan/python-deploy:latest
          EOF
